## Cross-Bucket Tests on all 3 Fragment Types using Kalman Filter

### Part A: (1) Import Fragment Data from MATLAB, (2) Save Them in a .pickle file, and (3) Load Them In

###### (HOWEVER, YOU DON'T NEED TO LOAD THEM IN AGAIN SINCE STEP 1 ALREADY DOES THAT FOR YOU!)

In [1]:
## (Configuration) Allows you to return multiple variables from a single cell ##
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

## Allows you to import files from another folder in current directory ## 
import os 
import sys 
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

## Import standard package ###
import numpy as np
from scipy import io
import sys

# Specify Fragment Types to be used for this Anaylsis 
frag_type = ['AD', 'HV', 'VM'] # ['AccDec', 'HillValley', 'VelMin']

In [2]:
## (NEW) Import Data ##
# We'll load in position data and derive velocity and acceleration from it 

folder = '/Users/rbhatt6/Documents/MATLAB/' # For Windows: folder='C:\\Users\\rbhatt1\\Downloads\\' 

 #locals()["sortIn"+frag_type[i]] = io.loadmat(folder+'cleanedSortIn.mat')
for i in range(len(frag_type)):
    input = "sortIn_"+frag_type[i]
    locals()[input] = io.loadmat(folder + input + '.mat')

    output = "sortOut_" + frag_type[i]
    locals()[output] = io.loadmat(folder + output + '.mat')

    locals()[input] = np.squeeze(list(locals()[input].values())[3])
    locals()[output] = np.squeeze(list(locals()[output].values())[3])

In [2]:
 ## (OLD) Import Data ## 
# We'll load in position data and derive velocity and acceleration from it 

folder = '/Users/rbhatt6/Documents/MATLAB/' # For Windows: folder='C:\\Users\\rbhatt1\\Downloads\\' 

 #locals()["sortIn"+frag_type[i]] = io.loadmat(folder+'cleanedSortIn.mat')
for i in range(len(frag_type)):
    input = "sortIn_"+frag_type[i]
    locals()[input] = io.loadmat(folder + input + '.mat')
   
    outputX = "sortX_"+frag_type[i]
    locals()[outputX] = io.loadmat(folder + outputX + '.mat')

    outputY = "sortY_"+frag_type[i]
    locals()[outputY] = io.loadmat(folder + outputY + '.mat')

    locals()[input] = np.squeeze(list(locals()[input].values())[3])
    locals()[outputX] = np.squeeze(list(locals()[outputX].values())[3])
    locals()[outputY] = np.squeeze(list(locals()[outputY].values())[3])

In [15]:
## (OLD) Save Data in .pickle files ## 
import pickle

data_folder='/Users/rbhatt6/Documents/MATLAB/' # Folder where you want to save the data

for i in range(len(frag_type)):
    input = "sortIn_"+frag_type[i]
    outputX = "sortX_"+frag_type[i]
    outputY = "sortY_"+frag_type[i]

    with open(data_folder + input + '.pickle','wb') as f:
        pickle.dump(locals()[input],f)

    with open(data_folder + outputX + '.pickle','wb') as f:
        pickle.dump(locals()[outputX],f)

    with open(data_folder + outputY + '.pickle','wb') as f:
        pickle.dump(locals()[outputY],f)

### Part B: Preprocessing Decoder Data

In [3]:
#Import standard packages
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from scipy import io
from scipy import stats
import pickle
import sys

#Import metrics
from Neural_Decoding.metrics import get_R2
from Neural_Decoding.metrics import get_rho
from Neural_Decoding.metrics import get_R2_parts

#Import decoder functions
from Neural_Decoding.decoders import KalmanFilterDecoder

In [4]:
# (NEW)
#For the Kalman filter, we use the position, velocity, and acceleration as outputs.
#Ultimately, we are only concerned with the goodness of fit of velocity, but using them all as covariates helps performance.

for i in range(len(frag_type)):
    # Pulling local variables into new, temp variables
    output = locals()["sortOut_"+frag_type[i]]
    
    # Creating a local variable for each decoder_output
    decoder_output = "decoder_output_" + frag_type[i]
    locals()[decoder_output] = []

    for j in range(len(output)): # Number of buckets (i.e. 16 or 8)
        nFrags = output[j][0].shape[0]
        temp2 = []
        for k in range(0, nFrags, 1): # Number of fragments #output[0][0].shape[0]
            vel_X = float(output[j][0][k])
            vel_Y = float(output[j][1][k])
            acc_X = float(output[j][2][k])
            acc_Y = float(output[j][3][k])
            pos_X = float(output[j][4][k])
            pos_Y = float(output[j][5][k])
            temp = [vel_X, vel_Y, acc_X, acc_Y, pos_X, pos_Y]
            temp2.append(np.array(temp))
            #locals()[decoder_output][j][k].append(np.array(temp))
        #locals()[decoder_output][j].append(np.array(temp2))
        locals()[decoder_output].append(np.array(temp2))
        #temp = np.array(np.concatenate((vel_X, vel_Y, acc_X, acc_Y, outputX[j], outputY[j]),axis=1))


In [19]:
decoder_output_HV
decoder_output_HV[0].shape
decoder_output_HV[0]
decoder_output_HV[0][0]

[array([[5.48556167e-01, 1.22865730e-01, 6.93827106e-03, 7.52705492e-04,
         5.37775254e+01, 2.10242300e+02],
        [6.76156425e-01, 4.18579085e-02, 8.41244485e-03, 1.83170876e-03,
         6.85346873e+01, 2.11452673e+02],
        [5.88164337e-01, 3.97377851e-02, 5.59732678e-03, 3.04124157e-03,
         7.66715545e+01, 2.13957506e+02],
        ...,
        [2.32727175e-01, 4.41851443e-02, 5.85209286e-04, 1.20064302e-04,
         4.44905051e+01, 2.29669567e+02],
        [2.75851990e-01, 2.67631928e-02, 9.38428766e-04, 6.24548552e-04,
         5.06914238e+01, 2.30540062e+02],
        [2.47780077e-01, 2.74673162e-02, 1.71836011e-03, 6.60716660e-04,
         5.40086753e+01, 2.30415294e+02]]),
 array([[3.07932042e-01, 9.58960320e-02, 3.29470420e-03, 1.29779564e-03,
         5.96029095e+01, 2.53581530e+02],
        [3.24533539e-01, 2.19790889e-01, 5.81649701e-03, 2.62078815e-03,
         5.69179329e+01, 2.60855802e+02],
        [1.60646279e-01, 3.01106027e-01, 4.83584272e-03, 4.838297

(1751, 6)

array([[5.48556167e-01, 1.22865730e-01, 6.93827106e-03, 7.52705492e-04,
        5.37775254e+01, 2.10242300e+02],
       [6.76156425e-01, 4.18579085e-02, 8.41244485e-03, 1.83170876e-03,
        6.85346873e+01, 2.11452673e+02],
       [5.88164337e-01, 3.97377851e-02, 5.59732678e-03, 3.04124157e-03,
        7.66715545e+01, 2.13957506e+02],
       ...,
       [2.32727175e-01, 4.41851443e-02, 5.85209286e-04, 1.20064302e-04,
        4.44905051e+01, 2.29669567e+02],
       [2.75851990e-01, 2.67631928e-02, 9.38428766e-04, 6.24548552e-04,
        5.06914238e+01, 2.30540062e+02],
       [2.47780077e-01, 2.74673162e-02, 1.71836011e-03, 6.60716660e-04,
        5.40086753e+01, 2.30415294e+02]])

array([5.48556167e-01, 1.22865730e-01, 6.93827106e-03, 7.52705492e-04,
       5.37775254e+01, 2.10242300e+02])

In [272]:
# (OLD)
#For the Kalman filter, we use the position, velocity, and acceleration as outputs.
#Ultimately, we are only concerned with the goodness of fit of velocity, but using them all as covariates helps performance.

for i in range(len(frag_type)):
    
    # Pulling local variables into new, temp variables
    outputX = locals()["sortX_"+frag_type[i]]
    outputY = locals()["sortY_"+frag_type[i]]
    
    # Creating a local variable for each decoder_output
    decoder_output = "decoder_output_" + frag_type[i]
    locals()[decoder_output] = []

    for j in range(len(outputX)):
        # Determine X and Y velocities 
        vel_X = (np.diff(outputX[j], axis = 0))      
        vel_X = np.concatenate((vel_X,vel_X[-1:,:]),axis=0)
        vel_Y = (np.diff(outputY[j], axis = 0))      
        vel_Y = np.concatenate((vel_Y,vel_Y[-1:,:]),axis=0)

        # Determine X and Y accelerations 
        acc_X = (np.diff(vel_X, axis = 0))   
        acc_X = np.concatenate((acc_X,acc_X[-1:,:]),axis=0)
        acc_Y = (np.diff(vel_Y, axis = 0))      
        acc_Y = np.concatenate((acc_Y,acc_Y[-1:,:]),axis=0)

        # Concatenating all 3 kinematics for X and Y components
        # Corrected decoder outputs (format = x,y vel, x,y acc, x,y pos)
        temp = np.array(np.concatenate((vel_X, vel_Y, acc_X, acc_Y, outputX[j], outputY[j]),axis=1))

        locals()[decoder_output].append(temp)

### Part C: Partitioning and Running the Kalman Filter on the Same Buckets 

In [5]:
#Set what part of data should be part of the training/testing/validation sets

training_range=[0, 0.8]
valid_range=[0.8,0.9]
testing_range=[0.9, 1]

In [6]:
# Running decoder on X and Y components together to get the prediction nom and denom to later compute the combined XY_FVAF
from Neural_Decoding.runModelsKF import run_model_kf

for i in range(len(frag_type)):

    # Pulling local variables 
    input = locals()["sortIn_"+frag_type[i]]
    output = locals()["decoder_output_"+frag_type[i]]

    # Creating a local variable to hold (X, Y) predicted outputs for each frag type 
    parts = "pred_parts_" + frag_type[i]
    locals()[parts] = run_model_kf(input, output, training_range, testing_range, valid_range, "parts")

In [7]:
# Compute combined XY_FVAF (velocity only)
from Neural_Decoding.metrics import compute_XY_FVAF

for i in range(len(frag_type)):

    # Pulling previously computed predicted_parts (i.e. nom and denom)
    parts = locals()[ "pred_parts_" + frag_type[i]]
    
    # Creating a local variable to hold XY_FVAFs each frag type 
    XY_FVAF = "XY_FVAF_" + frag_type[i]
    locals()[XY_FVAF] = []

    for j in range(len(parts)):
        #curr_bucket = Kalman_R2s_combined[i]
        vel_x_nom = parts[j][0][0] # dim = (curr_bucket, nom, x_vel)
        vel_x_denom = parts[j][1][0] # dim = (curr_bucket, denom, x_vel)
        vel_y_nom = parts[j][0][1] # dim = (curr_bucket, nom, y_vel)
        vel_y_denom = parts[j][1][1] # dim = (curr_bucket, denom, y_vel)

        curr_bucket_XY_FVAF = compute_XY_FVAF(vel_x_nom,vel_x_denom,vel_y_nom,vel_y_denom)
        locals()[XY_FVAF].append(curr_bucket_XY_FVAF)

In [11]:
XY_FVAF_AD

[0.274861529126343,
 0.17285629320953566,
 0.3689220685199799,
 0.359915096119927,
 0.4215025371900333,
 0.37625623031487165,
 0.4259858030424114,
 0.3695129756493417,
 0.18764753306435566,
 0.20314343596785345,
 0.18883410343142448,
 0.0813192122389158,
 0.07460811664925293,
 0.14498036696841665,
 0.04125201098470266,
 0.13951618425674284]

In [ ]:
for i in range(len(sortIn_AD)):
    X_kf = sortIn_AD[i]
    y_kf = decoder_output_AD[i]
    num_examples_kf=X_kf.shape[0] # nRows (b/c nCols = number of units)
    
    #Note that each range has a buffer of 1 bin at the beginning and end
    #This makes it so that the different sets don't include overlapping data
    training_set=np.arange(int(np.round(training_range[0]*num_examples_kf))+1,int(np.round(training_range[1]*num_examples_kf))-1)
    testing_set=np.arange(int(np.round(testing_range[0]*num_examples_kf))+1,int(np.round(testing_range[1]*num_examples_kf))-1)
    valid_set=np.arange(int(np.round(valid_range[0]*num_examples_kf))+1,int(np.round(valid_range[1]*num_examples_kf))-1)

    #Get training data
    X_kf_train=X_kf[training_set,:]
    y_kf_train=y_kf[training_set,:]

    #Get testing data
    X_kf_test=X_kf[testing_set,:]
    y_kf_test=y_kf[testing_set,:]

    #Get validation data
    X_kf_valid=X_kf[valid_set,:]
    y_kf_valid=y_kf[valid_set,:]

    #Z-score inputs 
    X_kf_train_mean=np.nanmean(X_kf_train,axis=0)
    X_kf_train_std=np.nanstd(X_kf_train,axis=0)
    X_kf_train=(X_kf_train-X_kf_train_mean)/X_kf_train_std
    X_kf_test=(X_kf_test-X_kf_train_mean)/X_kf_train_std
    X_kf_valid=(X_kf_valid-X_kf_train_mean)/X_kf_train_std

    #Zero-center outputs
    y_kf_train_mean=np.mean(y_kf_train,axis=0)
    y_kf_train=y_kf_train-y_kf_train_mean
    y_kf_test=y_kf_test-y_kf_train_mean
    y_kf_valid=y_kf_valid-y_kf_train_mean

    #Declare model
    model_kf=KalmanFilterDecoder(C=1) #There is one optional parameter (see ReadMe)

    #Fit model
    model_kf.fit(X_kf_train,y_kf_train)

    #Get predictions
    y_valid_predicted_kf=model_kf.predict(X_kf_valid,y_kf_valid)

    #Get metrics of fit (see read me for more details on the differences between metrics)
    #First I'll get the R^2
    R2_kf=get_R2(y_kf_valid,y_valid_predicted_kf)
    print('R2:',R2_kf[0:2]) #I'm just printing the R^2's of the 1st and 2nd entries that correspond to the positions
    #Next I'll get the rho^2 (the pearson correlation squared)


### Part D: Partitioning and Running the Kalman Filter on Separate Training and Test Buckets